title: Matthew Chambers
description: > # this means to ignore newlines until "baseurl:"
  My name is Matthew Chambers and I'm a web developer and digital marketer.
permalink: ':title/'
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Matthew Chambers # add your name
author-img: mattchambers.jpg # add your photo
about-author: I'm a digital marketer & web developer focusing on media buying and front-end development. Always hungry to keep learning. # add description
social-twitter: MattC_997
social-github: mattchambers # add your Github handle
social-linkedin: mattchambers9 # add your Linkedin handle
social-email: matt.keizergroup@gmail.com # add your Email address

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
